
OrdererOrgs:
  - Name: Orderer
    Domain: farmer.com
    Specs:
      - Hostname: orderer
  - Name: Orderer
    Domain: transport.com
    Specs:
      - Hostname: orderer
  - Name: Orderer
    Domain: supermarket.com
    Specs:
      - Hostname: orderer
  - Name: Orderer
    Domain: government.com
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: farmer
    Domain: farmer.com
    EnableNodeOUs: true
    CA:
      Hostname:  ca
    Specs:
      - Hostname: apple
      - Hostname: pear
      - Hostname: melon
    Users:
      Count: 3
  - Name: transport
    Domain: transport.com
    EnableNodeOUs: true
    CA:
      Hostname:  ca
    Specs:
      - Hostname: cargo.truck
      - Hostname: refrigerated.truck
    Users:
      Count: 2
  - Name: walmar
    Domain: supermarket.com
    EnableNodeOUs: true
    CA:
      Hostname:  ca
    Template:
      Count: 2
    Users:
      Count: 2
  - Name: tax
    Domain: government.com
    EnableNodeOUs: true
    CA:
      Hostname:  ca
    Template:
      Count: 2
    Users:
      Count: 2